### ISSUE TITLE
Rounded background of names

### ISSUE THREAD

**Issue by ziemniok99** [DevilsLynAvenged/DevilsLynAvenged#11]
Please do rounded background of nicknames 
![image](https://user-images.githubusercontent.com/43730820/63626575-00f90780-c604-11e9-9e8e-304a26a9c9a9.png)

**Comment by DevilsLynAvenged** [comment]
`.theme-dark .headerCozyMeta-rdohGq {
border-radius: 40px;
}` put this in the custom css if you want rounded background

**Comment by ziemniok99** [comment]
It worked ty
