### ISSUE TITLE
Boku No Hero Academia - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by XanderMC** [DevilsLynAvenged/DevilsLynAvenged#12]
Hi, please fix the download link because im a Boku no Hero fan and i want my discord to be that theme so please fix the download link. Thank you

**Comment by DevilsLynAvenged** [comment]
I removed it because too many people were inactive to the theme and I'm in progress in making a new one

**Comment by XanderMC** [comment]
Ok good luck with the work!

Vào Th 3, 3 thg 9, 2019 lúc 8:45 SA DevilsLynAvenged <
notifications@github.com> đã viết:
