### ISSUE TITLE
Boku No Hero Academia - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by ZenoSama1998** [DevilsLynAvenged/DevilsLynAvenged#17]
Error server failure or wrong URL
![18e4a6868998eb3e8d4119fe616a7f81](https://user-images.githubusercontent.com/55345493/64919172-e7cd1c00-d7a7-11e9-9677-7d94cb9c42bc.png)

**Comment by DevilsLynAvenged** [comment]
I removed it because too many people were inactive about it and I'm in a process in making a new one

**Comment by lol343434** [comment]
Hi,
I wanted to ask you if you can reupload the old one again. because there was a picture what moved me quite.
and it is quite a pity that it is gone  (bnha returns)
sry if i write it here as a comment but i dont know how i contact you.
Thanks and have a nice day.
