### ISSUE TITLE
Boku No Hero Academia - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by ZelLbI** [DevilsLynAvenged/DevilsLynAvenged#4]
I see that it's a mac based for the thumbnail so I'm not sure if this is just a windows issue or not but, at the top of the discord window it's in full color with no dim of black.

**Comment by DevilsLynAvenged** [comment]
hmmmm

**Comment by DevilsLynAvenged** [comment]
it's probably just a windows issue
