### ISSUE TITLE
Clear sunset theme

### ISSUE THREAD

**Issue by zeeklol** [DevilsLynAvenged/DevilsLynAvenged#6]
Pretty sure new discord update messed with a lot of things with this theme/many others. 
-- Selected channel doesn't have a color
-- Hovering over channels doesn't give a color
-- Muted categories don't turn red anymore
-- (Friends tab) https://gyazo.com/7d0269906acb6e4c5a7578dc6986d08b
Probably many other issues though. 

This wasn't an issue caused by the update but the "Activity" tab has plain, normal discord colours.

**Comment by DevilsLynAvenged** [comment]
I already took care of them
